---
FR4: # use the patient ID as the key
  S124: # use the sample ID as the key
    type: 'normal' # use 'normal' or 'tumour' as the value
    libraries:
      Stewart_241029_RNA: # use the library name as the key
        runlanes:
          L005:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L005_R1_001.fastq.gz" # use the path to the R1 fastq file as the value
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L005_R2_001.fastq.gz" # use the path to the R2 fastq file as the value
          L006:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L006_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L006_R2_001.fastq.gz"
          L007:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L007_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L007_R2_001.fastq.gz"
          L008:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L008_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L008_R2_001.fastq.gz"
  S125: # use the sample ID as the key  
    type: 'tumour' 
    libraries:
      Stewart_241029_RNA: # use the library name as the key
        runlanes:
          L005: 
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L005_R1_001.fastq.gz" 
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L005_R2_001.fastq.gz"
          L006:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L006_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L006_R2_001.fastq.gz"
          L007:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L007_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L007_R2_001.fastq.gz"
          L008:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L008_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L008_R2_001.fastq.gz"
  S123: # use the sample ID as the key  
    type: 'tumour' 
    libraries:
      Stewart_241029_RNA: # use the library name as the key
        runlanes:
          L005: 
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L005_R1_001.fastq.gz" 
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L005_R2_001.fastq.gz"
          L006:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L006_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L006_R2_001.fastq.gz"
          L007:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L007_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L007_R2_001.fastq.gz"
          L008:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L008_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4res_S123_L008_R2_001.fastq.gz"
  S122: # use the sample ID as the key  
    type: 'tumour'
    libraries:
      Stewart_241029_RNA: # use the library name as the key
        runlanes:
          L005: 
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L005_R1_001.fastq.gz" 
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L005_R2_001.fastq.gz"
          L006:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L006_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L006_R2_001.fastq.gz"
          L007:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L007_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L007_R2_001.fastq.gz"
          L008:
            fastq:
              R1: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L008_R1_001.fastq.gz"
              R2: "/cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4sen_S122_L008_R2_001.fastq.gz"
