---
  Patient_001: #use the patient ID as the key
    Sample_FR4EV: #use the sample ID as the key
      type: 'normal' #use 'normal' or 'tumour' as the value
      libraries:
        Stewart_241029_RNA: #use the library name as the key
          runlanes:
            S124_L005:  #use the runlane name as the key
              fastq:
                R1: /cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L005_R1_001.fastq.gz #use the path to the R1 fastq file as the value
                R2: /cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4EV_S124_L005_R2_001.fastq.gz #use the path to the R2 fastq file as the value
    Sample_FR4TP53INP1: # use the sample ID as the key
      type: 'tumour' # use 'normal' or 'tumour' as the value
      libraries:
        Stewart_241029_RNA: # use the library name as the key
          runlanes:
            S125_L005: # use the runlane name as the key
              fastq:
                R1: /cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L005_R1_001.fastq.gz # use the path to the R1 fastq file as the value
                R2: /cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA/FR4TP53INP1_S125_L005_R2_001.fastq.gz # use the path to the R2 fastq file as the value
