---
base_path: /cluster/projects/myelomagroup/Tobi_data_practice/20250131_LH00244_0248_B22VJNCLT3_Stewart_241029_RNA # define the base path
FR4: # use the patient ID as the key
  sen: # updated sample ID
    type: 'normal' # use 'normal' or 'tumour' as the value
    libraries:
      Stewart_241029_RNA: # use the library name as the key
        runlanes:
          S122_L005: &runlane_template #runlane_template set as anchor point for repeats
            fastq:
              R1: *base_path/FR4sen_S122_L005_R1_001.fastq.gz # use the path to the R1 fastq file as the value
              R2: *base_path/FR4sen_S122_L005_R2_001.fastq.gz # use the path to the R2 fastq file as the value
          S122_L006:
            <<: *runlane_template # reuse the runlane_template anchor to avoid duplication of common properties
            fastq:
              R1: *base_path/FR4sen_S122_L006_R1_001.fastq.gz
              R2: *base_path/FR4sen_S122_L006_R2_001.fastq.gz
          S122_L007:
            <<: *runlane_template
            fastq:
              R1: *base_path/FR4sen_S122_L007_R1_001.fastq.gz
              R2: *base_path/FR4sen_S122_L007_R2_001.fastq.gz
          S122_L008:
            <<: *runlane_template
            fastq:
              R1: *base_path/FR4sen_S122_L008_R1_001.fastq.gz
              R2: *base_path/FR4sen_S122_L008_R2_001.fastq.gz
  res: # updated sample ID
    type: 'tumour' # use 'normal' or 'tumour' as the value
    libraries:
      Stewart_241029_RNA: # use the library name as the key
        runlanes:
          S123_L005: &runlane_template2 # use the runlane name as the key
            fastq:
              R1: *base_path/FR4res_S123_L005_R1_001.fastq.gz 
              R2: *base_path/FR4res_S123_L005_R2_001.fastq.gz
          S123_L006:
            <<: *runlane_template2 # reuse the runlane_template2 anchor to avoid duplication of common properties
            fastq:
              R1: *base_path/FR4res_S123_L006_R1_001.fastq.gz
              R2: *base_path/FR4res_S123_L006_R2_001.fastq.gz
          S123_L007:
            <<: *runlane_template2
            fastq:
              R1: *base_path/FR4res_S123_L007_R1_001.fastq.gz
              R2: *base_path/FR4res_S123_L007_R2_001.fastq.gz
          S123_L008:
            <<: *runlane_template2
            fastq:
              R1: *base_path/FR4res_S123_L008_R1_001.fastq.gz
              R2: *base_path/FR4res_S123_L008_R2_001.fastq.gz